2022-02-12 20:29:52,498 INFO    MainThread:4228 [internal.py:wandb_internal():88] W&B internal server running at pid: 4228, started at: 2022-02-12 20:29:52.498566
2022-02-12 20:29:52,500 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: check_version
2022-02-12 20:29:52,501 INFO    WriterThread:4228 [datastore.py:open_for_write():77] open: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/run-167gnyxl.wandb
2022-02-12 20:29:52,503 DEBUG   SenderThread:4228 [sender.py:send():179] send: header
2022-02-12 20:29:52,503 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: check_version
2022-02-12 20:29:57,506 DEBUG   SenderThread:4228 [sender.py:send():179] send: run
2022-02-12 20:30:03,634 INFO    SenderThread:4228 [dir_watcher.py:__init__():168] watching files in: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files
2022-02-12 20:30:03,634 INFO    SenderThread:4228 [sender.py:_start_run_threads():704] run started: 167gnyxl with start time 1644679791
2022-02-12 20:30:03,634 DEBUG   SenderThread:4228 [sender.py:send():179] send: summary
2022-02-12 20:30:03,635 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: run_start
2022-02-12 20:30:03,637 INFO    SenderThread:4228 [sender.py:_save_file():829] saving file wandb-summary.json with policy end
2022-02-12 20:30:03,638 DEBUG   HandlerThread:4228 [meta.py:__init__():39] meta init
2022-02-12 20:30:03,638 DEBUG   HandlerThread:4228 [meta.py:__init__():53] meta init done
2022-02-12 20:30:03,638 DEBUG   HandlerThread:4228 [meta.py:probe():210] probe
2022-02-12 20:30:03,645 DEBUG   HandlerThread:4228 [meta.py:_setup_git():200] setup git
2022-02-12 20:30:03,682 DEBUG   HandlerThread:4228 [meta.py:_setup_git():207] setup git done
2022-02-12 20:30:03,683 DEBUG   HandlerThread:4228 [meta.py:_save_pip():57] save pip
2022-02-12 20:30:03,683 DEBUG   HandlerThread:4228 [meta.py:_save_pip():71] save pip done
2022-02-12 20:30:03,684 DEBUG   HandlerThread:4228 [meta.py:_save_conda():78] save conda
2022-02-12 20:30:04,640 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/wandb-summary.json
2022-02-12 20:30:04,640 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/requirements.txt
2022-02-12 20:30:04,640 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/conda-environment.yaml
2022-02-12 20:30:05,171 DEBUG   HandlerThread:4228 [meta.py:_save_conda():86] save conda done
2022-02-12 20:30:05,171 DEBUG   HandlerThread:4228 [meta.py:probe():252] probe done
2022-02-12 20:30:05,176 DEBUG   SenderThread:4228 [sender.py:send():179] send: files
2022-02-12 20:30:05,176 INFO    SenderThread:4228 [sender.py:_save_file():829] saving file wandb-metadata.json with policy now
2022-02-12 20:30:05,183 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: stop_status
2022-02-12 20:30:05,183 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: stop_status
2022-02-12 20:30:05,643 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/conda-environment.yaml
2022-02-12 20:30:05,644 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/wandb-metadata.json
2022-02-12 20:30:05,644 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:30:06,422 DEBUG   SenderThread:4228 [sender.py:send():179] send: config
2022-02-12 20:30:07,649 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:30:12,666 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/config.yaml
2022-02-12 20:30:17,680 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:30:18,841 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: log_artifact
2022-02-12 20:30:18,841 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: log_artifact
2022-02-12 20:30:20,214 INFO    Thread-11 :4228 [upload_job.py:push():133] Uploaded file /var/folders/t_/s5_fbxpn7_g2q89lqrxbq6j40000gn/T/tmp8xagl636wandb/1ah568tl-wandb-metadata.json
2022-02-12 20:30:21,429 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: stop_status
2022-02-12 20:30:24,498 INFO    Thread-13 :4228 [upload_job.py:push():88] Skipped uploading /Users/jelaleddin/.cache/wandb/artifacts/obj/md5/df/365277a232ad7cf90f578e18fb4eb0
2022-02-12 20:30:28,508 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: stop_status
2022-02-12 20:30:31,419 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: log_artifact
2022-02-12 20:30:31,420 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: log_artifact
2022-02-12 20:30:31,735 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:30:44,452 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: stop_status
2022-02-12 20:31:08,033 INFO    Thread-15 :4228 [upload_job.py:push():88] Skipped uploading /Users/jelaleddin/.cache/wandb/artifacts/obj/md5/73/c28099f1ea08c82270be000db00999
2022-02-12 20:31:28,259 DEBUG   SenderThread:4228 [sender.py:send():179] send: stats
2022-02-12 20:31:28,260 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: stop_status
2022-02-12 20:31:43,843 DEBUG   SenderThread:4228 [sender.py:send():179] send: stats
2022-02-12 20:31:43,844 DEBUG   SenderThread:4228 [sender.py:send():179] send: stats
2022-02-12 20:31:43,990 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:31:44,735 DEBUG   SenderThread:4228 [sender.py:send():179] send: telemetry
2022-02-12 20:31:44,736 DEBUG   SenderThread:4228 [sender.py:send():179] send: exit
2022-02-12 20:31:44,736 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: poll_exit
2022-02-12 20:31:44,739 INFO    SenderThread:4228 [sender.py:send_exit():287] handling exit code: 1
2022-02-12 20:31:44,740 INFO    SenderThread:4228 [sender.py:send_exit():295] send defer
2022-02-12 20:31:44,740 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: poll_exit
2022-02-12 20:31:44,750 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: defer
2022-02-12 20:31:44,753 INFO    HandlerThread:4228 [handler.py:handle_request_defer():141] handle defer: 0
2022-02-12 20:31:44,753 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: defer
2022-02-12 20:31:44,753 INFO    SenderThread:4228 [sender.py:send_request_defer():304] handle sender defer: 0
2022-02-12 20:31:44,754 INFO    SenderThread:4228 [sender.py:send_request_defer():342] send defer: 1
2022-02-12 20:31:44,755 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: defer
2022-02-12 20:31:44,755 INFO    HandlerThread:4228 [handler.py:handle_request_defer():141] handle defer: 1
2022-02-12 20:31:44,790 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: defer
2022-02-12 20:31:44,791 INFO    SenderThread:4228 [sender.py:send_request_defer():304] handle sender defer: 1
2022-02-12 20:31:44,791 INFO    SenderThread:4228 [sender.py:send_request_defer():342] send defer: 2
2022-02-12 20:31:44,791 DEBUG   SenderThread:4228 [sender.py:send():179] send: stats
2022-02-12 20:31:44,791 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: defer
2022-02-12 20:31:44,791 INFO    HandlerThread:4228 [handler.py:handle_request_defer():141] handle defer: 2
2022-02-12 20:31:44,792 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: defer
2022-02-12 20:31:44,792 INFO    SenderThread:4228 [sender.py:send_request_defer():304] handle sender defer: 2
2022-02-12 20:31:44,792 INFO    SenderThread:4228 [sender.py:send_request_defer():342] send defer: 3
2022-02-12 20:31:44,792 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: defer
2022-02-12 20:31:44,792 INFO    HandlerThread:4228 [handler.py:handle_request_defer():141] handle defer: 3
2022-02-12 20:31:44,792 DEBUG   SenderThread:4228 [sender.py:send():179] send: summary
2022-02-12 20:31:44,792 INFO    SenderThread:4228 [sender.py:_save_file():829] saving file wandb-summary.json with policy end
2022-02-12 20:31:44,793 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: defer
2022-02-12 20:31:44,793 INFO    SenderThread:4228 [sender.py:send_request_defer():304] handle sender defer: 3
2022-02-12 20:31:44,793 INFO    SenderThread:4228 [sender.py:send_request_defer():342] send defer: 4
2022-02-12 20:31:44,793 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: defer
2022-02-12 20:31:44,793 INFO    HandlerThread:4228 [handler.py:handle_request_defer():141] handle defer: 4
2022-02-12 20:31:44,793 DEBUG   SenderThread:4228 [sender.py:send_request():193] send_request: defer
2022-02-12 20:31:44,793 INFO    SenderThread:4228 [sender.py:send_request_defer():304] handle sender defer: 4
2022-02-12 20:31:44,857 DEBUG   HandlerThread:4228 [handler.py:handle_request():124] handle_request: poll_exit
2022-02-12 20:31:44,995 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/wandb-summary.json
2022-02-12 20:31:44,995 INFO    Thread-8  :4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:31:49,136 WARNING MainThread:4228 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-12 20:31:54,152 WARNING MainThread:4228 [internal.py:is_dead():366] Internal process exiting, parent pid 4221 disappeared
2022-02-12 20:31:54,152 ERROR   MainThread:4228 [internal.py:wandb_internal():143] Internal process shutdown.
2022-02-12 20:31:54,812 INFO    WriterThread:4228 [datastore.py:close():258] close: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/run-167gnyxl.wandb
2022-02-12 20:31:54,884 INFO    HandlerThread:4228 [handler.py:finish():638] shutting down handler
2022-02-12 20:32:05,751 INFO    SenderThread:4228 [sender.py:send_request_defer():342] send defer: 5
2022-02-12 20:32:05,752 INFO    SenderThread:4228 [sender.py:finish():933] shutting down sender
2022-02-12 20:32:05,752 INFO    SenderThread:4228 [dir_watcher.py:finish():282] shutting down directory watcher
2022-02-12 20:32:06,036 INFO    SenderThread:4228 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/config.yaml
2022-02-12 20:32:06,036 INFO    SenderThread:4228 [dir_watcher.py:finish():312] scan: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files
2022-02-12 20:32:06,037 INFO    SenderThread:4228 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/requirements.txt requirements.txt
2022-02-12 20:32:06,037 INFO    SenderThread:4228 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log output.log
2022-02-12 20:32:06,037 INFO    SenderThread:4228 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/config.yaml config.yaml
2022-02-12 20:32:06,040 INFO    SenderThread:4228 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/wandb-summary.json wandb-summary.json
2022-02-12 20:32:06,047 INFO    SenderThread:4228 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/conda-environment.yaml conda-environment.yaml
2022-02-12 20:32:06,051 INFO    SenderThread:4228 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/wandb-metadata.json wandb-metadata.json
2022-02-12 20:32:06,051 INFO    SenderThread:4228 [file_pusher.py:finish():176] shutting down file pusher
2022-02-12 20:32:06,051 INFO    SenderThread:4228 [file_pusher.py:join():181] waiting for file pusher
2022-02-12 20:32:10,505 INFO    Thread-17 :4228 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/output.log
2022-02-12 20:32:18,164 INFO    Thread-20 :4228 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/conda-environment.yaml
2022-02-12 20:32:21,217 INFO    Thread-19 :4228 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/wandb-summary.json
2022-02-12 20:32:24,564 ERROR   Thread-18 :4228 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-e22e9996835c795d42db199b2d7a286b1ecc7894/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-02-12 20:32:37,954 INFO    Thread-18 :4228 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_val_test_split/wandb/run-20220212_202951-167gnyxl/files/config.yaml
2022-02-12 22:32:08,566 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-12 22:55:47,452 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 00:37:04,977 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 01:19:47,848 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe4c5b0>: Failed to establish a new connection: [Errno 61] Connection refused')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 02:29:24,816 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fd82b20>: Failed to establish a new connection: [Errno 61] Connection refused')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 03:11:25,990 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fd827c0>: Failed to establish a new connection: [Errno 61] Connection refused')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 07:57:39,625 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe2edc0>: Failed to establish a new connection: [Errno 61] Connection refused')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:12:08,969 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fd93cd0>: Failed to establish a new connection: [Errno 61] Connection refused')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:18:12,079 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:29:42,947 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:30:45,111 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe3c190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:31:49,312 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe3cd00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:32:59,315 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe3c670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:37:03,734 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:38:23,272 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fdd0460>: Failed to establish a new connection: [Errno 60] Operation timed out')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:39:44,734 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fd82f40>: Failed to establish a new connection: [Errno 60] Operation timed out')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:40:53,606 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fd82a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:42:11,168 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/167gnyxl/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fd82a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 11:44:20,817 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-13 17:56:46,323 WARNING FileStreamThread:4228 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x10fda8040>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/167gnyxl/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
