
2022-02-15 16:37:19,195 Reading preprocessed data from Weights and Biases
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Project jelal/telco_churn does not contain artifact: "clean_telco.csv:latest"
Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/public.py", line 557, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/public.py", line 2759, in __init__
    self._load()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/public.py", line 3243, in _load
    raise ValueError(
ValueError: Project jelal/telco_churn does not contain artifact: "clean_telco.csv:latest"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_model/train_model.py", line 78, in <module>
    go(args)
  File "/Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/train_model/train_model.py", line 29, in go
    training_artifact = run.use_artifact(args.train_data).file()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2021, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/public.py", line 557, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/public.py", line 2759, in __init__
    self._load()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-ed3e60702d0de8e442bdd8c760d5ddec161b9573/lib/python3.9/site-packages/wandb/apis/public.py", line 3243, in _load
    raise ValueError(
wandb.errors.CommError: Project jelal/telco_churn does not contain artifact: "clean_telco.csv:latest"