2022-02-11 11:07:52,557 INFO    MainThread:76873 [internal.py:wandb_internal():88] W&B internal server running at pid: 76873, started at: 2022-02-11 11:07:52.557386
2022-02-11 11:07:52,559 DEBUG   HandlerThread:76873 [handler.py:handle_request():124] handle_request: check_version
2022-02-11 11:07:52,559 INFO    WriterThread:76873 [datastore.py:open_for_write():77] open: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/run-3m3p5lq8.wandb
2022-02-11 11:07:52,560 DEBUG   SenderThread:76873 [sender.py:send():179] send: header
2022-02-11 11:07:52,560 DEBUG   SenderThread:76873 [sender.py:send_request():193] send_request: check_version
2022-02-11 11:07:53,146 DEBUG   SenderThread:76873 [sender.py:send():179] send: run
2022-02-11 11:07:53,776 INFO    SenderThread:76873 [dir_watcher.py:__init__():168] watching files in: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files
2022-02-11 11:07:53,776 INFO    SenderThread:76873 [sender.py:_start_run_threads():704] run started: 3m3p5lq8 with start time 1644559671
2022-02-11 11:07:53,776 DEBUG   SenderThread:76873 [sender.py:send():179] send: summary
2022-02-11 11:07:53,776 INFO    SenderThread:76873 [sender.py:_save_file():829] saving file wandb-summary.json with policy end
2022-02-11 11:07:53,777 DEBUG   HandlerThread:76873 [handler.py:handle_request():124] handle_request: run_start
2022-02-11 11:07:53,779 DEBUG   HandlerThread:76873 [meta.py:__init__():39] meta init
2022-02-11 11:07:53,779 DEBUG   HandlerThread:76873 [meta.py:__init__():53] meta init done
2022-02-11 11:07:53,779 DEBUG   HandlerThread:76873 [meta.py:probe():210] probe
2022-02-11 11:07:53,780 DEBUG   HandlerThread:76873 [meta.py:_setup_git():200] setup git
2022-02-11 11:07:53,811 DEBUG   HandlerThread:76873 [meta.py:_setup_git():207] setup git done
2022-02-11 11:07:53,811 DEBUG   HandlerThread:76873 [meta.py:_save_pip():57] save pip
2022-02-11 11:07:53,811 DEBUG   HandlerThread:76873 [meta.py:_save_pip():71] save pip done
2022-02-11 11:07:53,812 DEBUG   HandlerThread:76873 [meta.py:_save_conda():78] save conda
2022-02-11 11:07:54,782 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/conda-environment.yaml
2022-02-11 11:07:54,783 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/requirements.txt
2022-02-11 11:07:54,783 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/wandb-summary.json
2022-02-11 11:07:55,293 DEBUG   HandlerThread:76873 [meta.py:_save_conda():86] save conda done
2022-02-11 11:07:55,293 DEBUG   HandlerThread:76873 [meta.py:probe():252] probe done
2022-02-11 11:07:55,298 DEBUG   SenderThread:76873 [sender.py:send():179] send: files
2022-02-11 11:07:55,298 INFO    SenderThread:76873 [sender.py:_save_file():829] saving file wandb-metadata.json with policy now
2022-02-11 11:07:55,303 DEBUG   HandlerThread:76873 [handler.py:handle_request():124] handle_request: stop_status
2022-02-11 11:07:55,304 DEBUG   SenderThread:76873 [sender.py:send_request():193] send_request: stop_status
2022-02-11 11:07:55,708 DEBUG   SenderThread:76873 [sender.py:send():179] send: config
2022-02-11 11:07:55,749 DEBUG   HandlerThread:76873 [handler.py:handle_request():124] handle_request: log_artifact
2022-02-11 11:07:55,749 DEBUG   SenderThread:76873 [sender.py:send_request():193] send_request: log_artifact
2022-02-11 11:07:55,783 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/conda-environment.yaml
2022-02-11 11:07:55,783 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/output.log
2022-02-11 11:07:55,784 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/wandb-metadata.json
2022-02-11 11:07:55,967 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:07:57,235 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:07:57,341 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:07:57,790 INFO    Thread-8  :76873 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/output.log
2022-02-11 11:07:58,620 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:07:59,821 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:07:59,822 ERROR   Thread-11 :76873 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1118, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1129, in upload_file
    util.sentry_reraise(retry.TransientException(exc=e))
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/util.py", line 121, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1118, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientException: None
2022-02-11 11:08:01,234 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:08:01,235 ERROR   Thread-13 :76873 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1118, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1129, in upload_file
    util.sentry_reraise(retry.TransientException(exc=e))
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/util.py", line 121, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1118, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jelaleddin/anaconda3/envs/mlflow-979f7f986a60824ce2cd07d3bd66e153f30e803a/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientException: None
2022-02-11 11:08:04,652 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:08:05,740 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:08:10,714 DEBUG   HandlerThread:76873 [handler.py:handle_request():124] handle_request: stop_status
2022-02-11 11:08:14,013 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:08:14,157 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:08:32,018 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:08:32,926 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:09:07,768 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:09:10,060 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:10:14,984 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:10:29,420 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:12:49,905 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:13:06,688 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:17:44,503 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:17:46,758 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:23:20,850 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:23:34,817 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:28:44,115 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:29:13,896 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:34:10,628 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:34:50,622 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:39:44,012 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:39:54,859 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:45:27,882 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:45:56,661 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:50:13,813 WARNING FileStreamThread:76873 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa8e0a116a0>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/3m3p5lq8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-11 11:50:16,266 WARNING FileStreamThread:76873 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/3m3p5lq8/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8e0cf7a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa8e0a116a0>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/3m3p5lq8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-11 11:51:35,362 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:51:45,023 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:56:56,126 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 11:57:30,484 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:03:11,320 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:03:26,949 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:06:19,584 WARNING MainThread:76873 [internal.py:wandb_internal():147] Internal process interrupt: 1
2022-02-11 12:06:19,974 WARNING MainThread:76873 [internal.py:wandb_internal():147] Internal process interrupt: 2
2022-02-11 12:06:19,974 ERROR   MainThread:76873 [internal.py:wandb_internal():150] Internal process interrupted.
2022-02-11 12:06:20,824 INFO    HandlerThread:76873 [handler.py:finish():638] shutting down handler
2022-02-11 12:06:20,832 INFO    WriterThread:76873 [datastore.py:close():258] close: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/run-3m3p5lq8.wandb
2022-02-11 12:08:40,216 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:09:03,364 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:14:32,858 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:15:05,800 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:34:31,050 WARNING FileStreamThread:76873 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa8e0a116a0>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/3m3p5lq8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-11 12:34:33,396 WARNING FileStreamThread:76873 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/jelal/telco_churn/3m3p5lq8/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8e0ca6d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa8e0a116a0>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/3m3p5lq8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-11 12:35:04,540 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:35:27,525 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:40:47,922 ERROR   Thread-13 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/jelal/telco_churn/wandb_artifacts/11389915/78873824/0f9de68e012bd3aed5fa7cdc9fc421af?Expires=1644646077&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=YhTj2w5nKOdug%2BgPs%2BlS1DEZUAYIV3oT1nNPfhWGwRPJQ0l8ZkdMm9F3zzIexNpixR3z79LuhyrDKTkuuHqkqOL9DtPGIXE7YinzpUJ%2F5u7DWf5bU5bqY8luFlgQoT1m0bVzFyvb9s3EkiSOb6BcLGnNvIolfZZFqztHmOk%2FgyLHjbWz3N61T3xgrzjXqyLEsxoC9frOUgSufsqvRmzkc1zUx7oMLE4mAN6ZcrE6MScq%2B5yGtGJlJ1TKc3eWMxLOzhMDJL5mxsja%2FnETASK8ELZgku%2BSgV4v3mAVj4vutHldTE2TCCx8YQzY9YkXHzUa7fsBLhSRFZN9JnPiObhShA%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:41:09,374 ERROR   Thread-11 :76873 [internal_api.py:upload_file():1121] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/jelal/telco_churn/3m3p5lq8/wandb-metadata.json?Expires=1644646075&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Ip%2FPe0%2Fx5jwpE7t7ch5XTRZP3CwUyUK%2F5yiVN3pnv7S%2FUz2DqcxFdT6%2FYrC18%2FZ%2B0hW%2BbcBBLerPMw28qp6Fe3EpsY8C1nQ6ULMms%2F0iFiorq5R2P36DaRJLEotJrlmuSEWnT2%2FLweOsloOf3toyIncID8LO65MA5MvpGjawS2lb8w2dDrT5nlr9X260SZnveChJPfMUEH5MjL7Mbc7VltPFS4rcMUuaX%2BnELnuD%2BzlOPUHhIbLYcHK%2Fx8FBDDMKXH5vSNrmLYkAEru6lqfHKrFoqjynCiRgxhIHpI4m9z6gECzZbrnv8eVSjwGtOA6NnVqUQlTD1CxWjklOS8L%2BRw%3D%3D ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2022-02-11 12:46:16,033 INFO    Thread-11 :76873 [upload_job.py:push():133] Uploaded file /var/folders/t_/s5_fbxpn7_g2q89lqrxbq6j40000gn/T/tmpoynh6_bvwandb/xdqpsto7-wandb-metadata.json
2022-02-11 12:46:37,450 INFO    Thread-13 :76873 [upload_job.py:push():91] Uploaded file /Users/jelaleddin/.cache/wandb/artifacts/obj/md5/0f/9de68e012bd3aed5fa7cdc9fc421af
2022-02-11 12:46:40,515 INFO    SenderThread:76873 [sender.py:finish():933] shutting down sender
2022-02-11 12:46:40,515 INFO    SenderThread:76873 [dir_watcher.py:finish():282] shutting down directory watcher
2022-02-11 12:46:41,248 INFO    SenderThread:76873 [dir_watcher.py:finish():312] scan: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files
2022-02-11 12:46:41,249 INFO    SenderThread:76873 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/requirements.txt requirements.txt
2022-02-11 12:46:41,249 INFO    SenderThread:76873 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/output.log output.log
2022-02-11 12:46:41,256 INFO    SenderThread:76873 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/config.yaml config.yaml
2022-02-11 12:46:41,267 INFO    SenderThread:76873 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/wandb-summary.json wandb-summary.json
2022-02-11 12:46:41,268 INFO    SenderThread:76873 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/conda-environment.yaml conda-environment.yaml
2022-02-11 12:46:41,274 INFO    SenderThread:76873 [dir_watcher.py:finish():318] scan save: /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/wandb-metadata.json wandb-metadata.json
2022-02-11 12:46:41,275 INFO    SenderThread:76873 [file_pusher.py:finish():176] shutting down file pusher
2022-02-11 12:46:41,276 INFO    SenderThread:76873 [file_pusher.py:join():181] waiting for file pusher
2022-02-11 12:46:44,133 INFO    Thread-14 :76873 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/requirements.txt
2022-02-11 12:46:44,145 INFO    Thread-17 :76873 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/wandb-summary.json
2022-02-11 12:46:44,172 INFO    Thread-15 :76873 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/output.log
2022-02-11 12:46:44,227 INFO    Thread-18 :76873 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/conda-environment.yaml
2022-02-11 12:46:44,256 INFO    Thread-16 :76873 [upload_job.py:push():133] Uploaded file /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/get_data/wandb/run-20220211_110751-3m3p5lq8/files/config.yaml
2022-02-11 12:46:47,446 WARNING FileStreamThread:76873 [file_stream.py:request_with_retry():429] requests_with_retry encountered retryable exception: ('Connection aborted.', OSError(65, 'No route to host')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fa8e0a116a0>>, args: ('https://api.wandb.ai/files/jelal/telco_churn/3m3p5lq8/file_stream',), kwargs: {'json': {'complete': False, 'failed': False}}
2022-02-11 12:46:51,147 INFO    MainThread:76873 [internal.py:handle_exit():78] Internal process exited
